#InputBooster v3.0.0 Configuration \u2014 by Ahaduzzaman Khan
#Sat Jul 25 12:53:46 CDT 2026
anti_idle=true
auto_sprint=true
auto_strafe=true
burst_mode=true
combo_keys=true
config_version=301
cps_limiter=true
cps_mode=FIXED
debug_mode=false
event_log=true
fps_check_interval=20
key_conflict_warn=true
max_cps=20
overlay_opacity=0.8
overlay_position=0
overlay_scale=1.0
per_server_profiles=true
poll_rate_auto=true
poll_rate_hz=200
replay_enabled=true
safe_mode=true
show_action_bar=true
show_f3_info=false
show_keystrokes=true
sprint_fix=true
wtap_assist=true
